// Sample slate datasets for Fantasy Grinder DFS Optimizer
// Ported from realistic DraftKings slates for MMA, NBA, and Golf.
// Complete with high-resolution athlete headshots, team badges, and metrics.

export const SAMPLE_MMA_FIGHTERS = [
  { 
    id: 'mma-1', 
    name: 'Jon Jones', 
    salary: 10000, 
    projection: 30.0, 
    dkAvgPoints: 30.0, 
    gameInfo: 'Jones vs Aspinall', 
    projectedOwnership: 38.5, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335639.png&w=350&h=254'
  },
  { 
    id: 'mma-2', 
    name: 'Islam Makhachev', 
    salary: 9800, 
    projection: 28.5, 
    dkAvgPoints: 28.5, 
    gameInfo: 'Makhachev vs Oliveira', 
    projectedOwnership: 35.2, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/h24pnq1705940288.png'
  },
  { 
    id: 'mma-3', 
    name: 'Alex Pereira', 
    salary: 9600, 
    projection: 27.0, 
    dkAvgPoints: 27.0, 
    gameInfo: 'Pereira vs Adesanya', 
    projectedOwnership: 32.8, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/3a9h2j1728206945.png'
  },
  { 
    id: 'mma-4', 
    name: 'Tom Aspinall', 
    salary: 9400, 
    projection: 26.5, 
    dkAvgPoints: 26.5, 
    gameInfo: 'Jones vs Aspinall', 
    projectedOwnership: 29.4, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/e53fep1725180232.png'
  },
  { 
    id: 'mma-5', 
    name: 'Charles Oliveira', 
    salary: 9200, 
    projection: 25.0, 
    dkAvgPoints: 25.0, 
    gameInfo: 'Makhachev vs Oliveira', 
    projectedOwnership: 27.1, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/5zm0ds1588786922.png'
  },
  { 
    id: 'mma-6', 
    name: 'Ilia Topuria', 
    salary: 9000, 
    projection: 24.0, 
    dkAvgPoints: 24.0, 
    gameInfo: 'Topuria vs Volkanovski', 
    projectedOwnership: 26.5, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/cz7spq1706003785.png'
  },
  { 
    id: 'mma-7', 
    name: 'Dricus Du Plessis', 
    salary: 8800, 
    projection: 23.0, 
    dkAvgPoints: 23.0, 
    gameInfo: 'Du Plessis vs Strickland', 
    projectedOwnership: 25.0, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/ifm7ht1705939905.png'
  },
  { 
    id: 'mma-8', 
    name: 'Israel Adesanya', 
    salary: 8800, 
    projection: 22.5, 
    dkAvgPoints: 22.5, 
    gameInfo: 'Pereira vs Adesanya', 
    projectedOwnership: 24.0, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/x5kzjb1593611527.png'
  },
  { 
    id: 'mma-9', 
    name: 'Sean O\'Malley', 
    salary: 8600, 
    projection: 21.0, 
    dkAvgPoints: 21.0, 
    gameInfo: 'O\'Malley vs Dvalishvili', 
    projectedOwnership: 22.8, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/cki55v1692640323.png'
  },
  { 
    id: 'mma-10', 
    name: 'Khamzat Chimaev', 
    salary: 8600, 
    projection: 22.0, 
    dkAvgPoints: 22.0, 
    gameInfo: 'Chimaev vs Usman', 
    projectedOwnership: 23.4, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/9isx081732796281.png'
  },
  { 
    id: 'mma-11', 
    name: 'Alexander Volkanovski', 
    salary: 8400, 
    projection: 20.5, 
    dkAvgPoints: 20.5, 
    gameInfo: 'Topuria vs Volkanovski', 
    projectedOwnership: 21.5, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/cohkwk1593609654.png'
  },
  { 
    id: 'mma-12', 
    name: 'Justin Gaethje', 
    salary: 8200, 
    projection: 19.0, 
    dkAvgPoints: 19.0, 
    gameInfo: 'Poirier vs Gaethje', 
    projectedOwnership: 20.2, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/vstc9p1690818737.png'
  },
  { 
    id: 'mma-13', 
    name: 'Max Holloway', 
    salary: 8200, 
    projection: 19.5, 
    dkAvgPoints: 19.5, 
    gameInfo: 'Holloway vs Allen', 
    projectedOwnership: 20.8, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/gphp791594584009.png'
  },
  { 
    id: 'mma-14', 
    name: 'Merab Dvalishvili', 
    salary: 8000, 
    projection: 18.5, 
    dkAvgPoints: 18.5, 
    gameInfo: 'O\'Malley vs Dvalishvili', 
    projectedOwnership: 19.5, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/ecb6yk1726476068.png'
  },
  { 
    id: 'mma-15', 
    name: 'Leon Edwards', 
    salary: 8000, 
    projection: 18.0, 
    dkAvgPoints: 18.0, 
    gameInfo: 'Muhammad vs Edwards', 
    projectedOwnership: 18.9, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/o9got21705940668.png'
  },
  { 
    id: 'mma-16', 
    name: 'Dustin Poirier', 
    salary: 7800, 
    projection: 17.5, 
    dkAvgPoints: 17.5, 
    gameInfo: 'Poirier vs Gaethje', 
    projectedOwnership: 18.0, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/bhr5nw1611487577.png'
  },
  { 
    id: 'mma-17', 
    name: 'Sean Strickland', 
    salary: 7800, 
    projection: 17.0, 
    dkAvgPoints: 17.0, 
    gameInfo: 'Du Plessis vs Strickland', 
    projectedOwnership: 17.3, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/2r3vm91705939760.png'
  },
  { 
    id: 'mma-18', 
    name: 'Robert Whittaker', 
    salary: 7600, 
    projection: 16.5, 
    dkAvgPoints: 16.5, 
    gameInfo: 'Whittaker vs Costa', 
    projectedOwnership: 16.8, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/f938x41594500739.png'
  },
  { 
    id: 'mma-19', 
    name: 'Belal Muhammad', 
    salary: 7600, 
    projection: 16.0, 
    dkAvgPoints: 16.0, 
    gameInfo: 'Muhammad vs Edwards', 
    projectedOwnership: 16.0, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/1zpxo31650211603.png'
  },
  { 
    id: 'mma-20', 
    name: 'Kamaru Usman', 
    salary: 7400, 
    projection: 15.5, 
    dkAvgPoints: 15.5, 
    gameInfo: 'Chimaev vs Usman', 
    projectedOwnership: 15.2, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/693bru1593611045.png'
  },
  { 
    id: 'mma-21', 
    name: 'Arnold Allen', 
    salary: 7400, 
    projection: 14.5, 
    dkAvgPoints: 14.5, 
    gameInfo: 'Holloway vs Allen', 
    projectedOwnership: 14.0, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/28danv1684318490.png'
  },
  { 
    id: 'mma-22', 
    name: 'Valentina Shevchenko', 
    salary: 7200, 
    projection: 15.0, 
    dkAvgPoints: 15.0, 
    gameInfo: 'Shevchenko vs Grasso', 
    projectedOwnership: 14.5, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/m7byug1726477092.png'
  },
  { 
    id: 'mma-23', 
    name: 'Alexa Grasso', 
    salary: 7000, 
    projection: 13.5, 
    dkAvgPoints: 13.5, 
    gameInfo: 'Shevchenko vs Grasso', 
    projectedOwnership: 12.8, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/ksbovb1725792074.png'
  },
  { 
    id: 'mma-24', 
    name: 'Paulo Costa', 
    salary: 7000, 
    projection: 12.5, 
    dkAvgPoints: 12.5, 
    gameInfo: 'Whittaker vs Costa', 
    projectedOwnership: 11.5, 
    isLocked: false, 
    isExcluded: false, 
    minExposure: 0, 
    maxExposure: 100, 
    boost: 0,
    avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/i5kjx01717528122.png'
  },
];

export const SAMPLE_NBA_PLAYERS = [
  { id: 'nba-1', name: 'Nikola Jokic', team: 'DEN', opponent: 'GSW', positions: ['C'], salary: 11800, projection: 64.0, gameInfo: 'DEN@GSW 10:00PM ET', projectedOwnership: 34.2, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3112335.png&w=350&h=254' },
  { id: 'nba-2', name: 'Luka Doncic', team: 'DAL', opponent: 'LAL', positions: ['PG'], salary: 11600, projection: 62.5, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 32.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3945274.png&w=350&h=254' },
  { id: 'nba-3', name: 'Giannis Antetokounmpo', team: 'MIL', opponent: 'BOS', positions: ['PF', 'C'], salary: 11200, projection: 59.0, gameInfo: 'BOS@MIL 07:30PM ET', projectedOwnership: 29.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3032977.png&w=350&h=254' },
  { id: 'nba-4', name: 'Shai Gilgeous-Alexander', team: 'OKC', opponent: 'HOU', positions: ['PG'], salary: 10800, projection: 56.0, gameInfo: 'HOU@OKC 08:00PM ET', projectedOwnership: 27.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4278077.png&w=350&h=254' },
  { id: 'nba-5', name: 'Anthony Davis', team: 'LAL', opponent: 'DAL', positions: ['PF', 'C'], salary: 10200, projection: 53.0, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 25.1, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6583.png&w=350&h=254' },
  { id: 'nba-6', name: 'Jayson Tatum', team: 'BOS', opponent: 'MIL', positions: ['SF', 'PF'], salary: 9900, projection: 50.5, gameInfo: 'BOS@MIL 07:30PM ET', projectedOwnership: 24.2, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065648.png&w=350&h=254' },
  { id: 'nba-7', name: 'Domantas Sabonis', team: 'SAC', opponent: 'PHX', positions: ['PF', 'C'], salary: 9600, projection: 49.0, gameInfo: 'PHX@SAC 10:00PM ET', projectedOwnership: 23.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3155942.png&w=350&h=254' },
  { id: 'nba-8', name: 'LeBron James', team: 'LAL', opponent: 'DAL', positions: ['SF', 'PF'], salary: 9200, projection: 47.0, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 22.4, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/1966.png&w=350&h=254' },
  { id: 'nba-9', name: 'Kevin Durant', team: 'PHX', opponent: 'SAC', positions: ['SF', 'PF'], salary: 9100, projection: 46.0, gameInfo: 'PHX@SAC 10:00PM ET', projectedOwnership: 21.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3202.png&w=350&h=254' },
  { id: 'nba-10', name: 'Stephen Curry', team: 'GSW', opponent: 'DEN', positions: ['PG'], salary: 8900, projection: 44.5, gameInfo: 'DEN@GSW 10:00PM ET', projectedOwnership: 20.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3975.png&w=350&h=254' },
  { id: 'nba-11', name: 'Jalen Brunson', team: 'NYK', opponent: 'IND', positions: ['PG'], salary: 8800, projection: 45.0, gameInfo: 'NYK@IND 07:00PM ET', projectedOwnership: 21.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3934672.png&w=350&h=254' },
  { id: 'nba-12', name: 'Devin Booker', team: 'PHX', opponent: 'SAC', positions: ['PG', 'SG'], salary: 8700, projection: 43.5, gameInfo: 'PHX@SAC 10:00PM ET', projectedOwnership: 19.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3136193.png&w=350&h=254' },
  { id: 'nba-13', name: 'Tyrese Haliburton', team: 'IND', opponent: 'NYK', positions: ['PG'], salary: 8600, projection: 43.0, gameInfo: 'NYK@IND 07:00PM ET', projectedOwnership: 19.2, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4396993.png&w=350&h=254' },
  { id: 'nba-14', name: 'Kyrie Irving', team: 'DAL', opponent: 'LAL', positions: ['PG', 'SG'], salary: 8500, projection: 42.5, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 18.7, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6442.png&w=350&h=254' },
  { id: 'nba-15', name: 'Tyrese Maxey', team: 'PHI', opponent: 'MIA', positions: ['PG', 'SG'], salary: 8400, projection: 42.0, gameInfo: 'PHI@MIA 07:30PM ET', projectedOwnership: 18.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431678.png&w=350&h=254' },
  { id: 'nba-16', name: 'De\'Aaron Fox', team: 'SAC', opponent: 'PHX', positions: ['PG'], salary: 8200, projection: 41.0, gameInfo: 'PHX@SAC 10:00PM ET', projectedOwnership: 17.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066259.png&w=350&h=254' },
  { id: 'nba-17', name: 'Jaylen Brown', team: 'BOS', opponent: 'MIL', positions: ['SG', 'SF'], salary: 8000, projection: 40.0, gameInfo: 'BOS@MIL 07:30PM ET', projectedOwnership: 16.9, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3917376.png&w=350&h=254' },
  { id: 'nba-18', name: 'Bam Adebayo', team: 'MIA', opponent: 'PHI', positions: ['C'], salary: 7900, projection: 39.5, gameInfo: 'PHI@MIA 07:30PM ET', projectedOwnership: 16.2, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066261.png&w=350&h=254' },
  { id: 'nba-19', name: 'Derrick White', team: 'BOS', opponent: 'MIL', positions: ['PG', 'SG'], salary: 6500, projection: 32.0, gameInfo: 'BOS@MIL 07:30PM ET', projectedOwnership: 14.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3078576.png&w=350&h=254' },
  { id: 'nba-20', name: 'Austin Reaves', team: 'LAL', opponent: 'DAL', positions: ['PG', 'SG'], salary: 6100, projection: 29.5, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 13.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066457.png&w=350&h=254' },
  { id: 'nba-21', name: 'Aaron Gordon', team: 'DEN', opponent: 'GSW', positions: ['PF'], salary: 5800, projection: 28.0, gameInfo: 'DEN@GSW 10:00PM ET', projectedOwnership: 13.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3064290.png&w=350&h=254' },
  { id: 'nba-22', name: 'Jonathan Kuminga', team: 'GSW', opponent: 'DEN', positions: ['PF'], salary: 5600, projection: 27.5, gameInfo: 'DEN@GSW 10:00PM ET', projectedOwnership: 12.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433247.png&w=350&h=254' },
  { id: 'nba-23', name: 'P.J. Washington', team: 'DAL', opponent: 'LAL', positions: ['PF'], salary: 5400, projection: 26.0, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 12.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4278078.png&w=350&h=254' },
  { id: 'nba-24', name: 'Daniel Gafford', team: 'DAL', opponent: 'LAL', positions: ['C'], salary: 5200, projection: 25.5, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 11.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://sleepercdn.com/content/nba/players/1997.jpg' },
  { id: 'nba-25', name: 'Christian Braun', team: 'DEN', opponent: 'GSW', positions: ['SG', 'SF'], salary: 4900, projection: 24.0, gameInfo: 'DEN@GSW 10:00PM ET', projectedOwnership: 11.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431767.png&w=350&h=254' },
  { id: 'nba-26', name: 'Brandin Podziemski', team: 'GSW', opponent: 'DEN', positions: ['PG', 'SG'], salary: 4600, projection: 22.0, gameInfo: 'DEN@GSW 10:00PM ET', projectedOwnership: 10.2, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4683689.png&w=350&h=254' },
  { id: 'nba-27', name: 'Dereck Lively II', team: 'DAL', opponent: 'LAL', positions: ['C'], salary: 4400, projection: 23.5, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 12.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4683688.png&w=350&h=254' },
  { id: 'nba-28', name: 'Payton Pritchard', team: 'BOS', opponent: 'MIL', positions: ['PG'], salary: 4200, projection: 21.0, gameInfo: 'BOS@MIL 07:30PM ET', projectedOwnership: 9.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066354.png&w=350&h=254' },
  { id: 'nba-29', name: 'Sam Hauser', team: 'BOS', opponent: 'MIL', positions: ['SF'], salary: 3800, projection: 18.5, gameInfo: 'BOS@MIL 07:30PM ET', projectedOwnership: 8.4, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065804.png&w=350&h=254' },
  { id: 'nba-30', name: 'Moses Moody', team: 'GSW', opponent: 'DEN', positions: ['SG'], salary: 3600, projection: 17.5, gameInfo: 'DEN@GSW 10:00PM ET', projectedOwnership: 7.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432171.png&w=350&h=254' },
  { id: 'nba-31', name: 'Christian Wood', team: 'LAL', opponent: 'DAL', positions: ['C'], salary: 3400, projection: 16.0, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 6.9, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://sleepercdn.com/content/nba/players/1600.jpg' },
  { id: 'nba-32', name: 'Christian Koloko', team: 'LAL', opponent: 'DAL', positions: ['C'], salary: 3200, projection: 14.0, gameInfo: 'LAL@DAL 07:30PM ET', projectedOwnership: 5.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432822.png&w=350&h=254' },
];

export const SAMPLE_GOLF_PLAYERS = [
  { id: 'golf-1', name: 'Scottie Scheffler', salary: 12500, projection: 98.5, projectedOwnership: 36.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/9478.png&w=350&h=254' },
  { id: 'golf-2', name: 'Rory McIlroy', salary: 11400, projection: 89.0, projectedOwnership: 31.2, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/3470.png&w=350&h=254' },
  { id: 'golf-3', name: 'Xander Schauffele', salary: 11000, projection: 86.5, projectedOwnership: 29.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/10140.png&w=350&h=254' },
  { id: 'golf-4', name: 'Collin Morikawa', salary: 10400, projection: 81.0, projectedOwnership: 26.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/10592.png&w=350&h=254' },
  { id: 'golf-5', name: 'Ludvig Aberg', salary: 9900, projection: 78.5, projectedOwnership: 25.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://r2.thesportsdb.com/images/media/player/cutout/8b3yh71688997386.png' },
  { id: 'golf-6', name: 'Viktor Hovland', salary: 9500, projection: 74.0, projectedOwnership: 23.4, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/10596.png&w=350&h=254' },
  { id: 'golf-7', name: 'Hideki Matsuyama', salary: 9200, projection: 72.5, projectedOwnership: 22.1, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/5860.png&w=350&h=254' },
  { id: 'golf-8', name: 'Patrick Cantlay', salary: 8900, projection: 69.5, projectedOwnership: 21.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/6007.png&w=350&h=254' },
  { id: 'golf-9', name: 'Tommy Fleetwood', salary: 8600, projection: 67.0, projectedOwnership: 19.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/5539.png&w=350&h=254' },
  { id: 'golf-10', name: 'Tony Finau', salary: 8300, projection: 65.5, projectedOwnership: 18.7, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/2230.png&w=350&h=254' },
  { id: 'golf-11', name: 'Justin Thomas', salary: 8000, projection: 63.0, projectedOwnership: 17.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/4848.png&w=350&h=254' },
  { id: 'golf-12', name: 'Sahith Theegala', salary: 7800, projection: 61.5, projectedOwnership: 16.9, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_51634' },
  { id: 'golf-13', name: 'Max Homa', salary: 7600, projection: 59.0, projectedOwnership: 15.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/8974.png&w=350&h=254' },
  { id: 'golf-14', name: 'Sungjae Im', salary: 7500, projection: 58.5, projectedOwnership: 15.2, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_39971' },
  { id: 'golf-15', name: 'Tom Kim', salary: 7400, projection: 57.0, projectedOwnership: 14.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_52381' },
  { id: 'golf-16', name: 'Shane Lowry', salary: 7300, projection: 56.5, projectedOwnership: 14.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_34331' },
  { id: 'golf-17', name: 'Corey Conners', salary: 7200, projection: 55.0, projectedOwnership: 13.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/10488.png' },
  { id: 'golf-18', name: 'Keegan Bradley', salary: 7100, projection: 54.0, projectedOwnership: 13.0, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_28237' },
  { id: 'golf-19', name: 'Russell Henley', salary: 7000, projection: 53.5, projectedOwnership: 12.5, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_34046' },
  { id: 'golf-20', name: 'Min Woo Lee', salary: 6900, projection: 52.0, projectedOwnership: 11.9, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/11186.png' },
  { id: 'golf-21', name: 'Brian Harman', salary: 6800, projection: 51.5, projectedOwnership: 11.4, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://a.espncdn.com/combiner/i?img=/i/headshots/golf/players/full/3519.png' },
  { id: 'golf-22', name: 'Christiaan Bezuidenhout', salary: 6700, projection: 50.0, projectedOwnership: 10.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_46970' },
  { id: 'golf-23', name: 'Denny McCarthy', salary: 6600, projection: 49.5, projectedOwnership: 10.2, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_40058' },
  { id: 'golf-24', name: 'Harris English', salary: 6500, projection: 48.0, projectedOwnership: 9.8, isLocked: false, isExcluded: false, minExposure: 0, maxExposure: 100, boost: 0, avatarUrl: 'https://pga-tour-res.cloudinary.com/image/upload/c_fill,g_face:center,q_auto,f_auto,dpr_2.0,h_220,w_200,d_stub:default_avatar_light.webp/headshots_35368' },
];
